alias ga="git add"
alias gb="git branch"
alias go="git checkout "
alias gs="git status"
alias gp="git push origin HEAD"
alias glog="git log --graph --oneline --all --decorate"
alias amend="git commit --amend"
