alias ga="git add"
alias gac="git add . && git commit -m"
alias gb="git branch --sort=committerdate"
alias go="git checkout "
alias gs="git status"
alias gp="git push origin HEAD"
alias gpf="git push origin HEAD --force-with-lease"
alias gl="git pull"
alias glom="git pull origin master"
alias glog="git log --graph --oneline --decorate"
alias gwip="git commit -anm wip"
alias amend="git commit --amend"
