tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "git"
brew "antibody"
brew "asdf"
brew "redis"
brew "ruby-build"
brew "zsh"
brew "direnv"


# Asdf dependencies
brew "coreutils"
brew "automake"
brew "autoconf"
brew "openssl"
brew "libyaml"
brew "readline"
brew "libxslt"
brew "libtool"
brew "unixodbc"
brew "unzip"
brew "curl"
brew "gpg"
cask "font-fira-code"

